version: "3"
services:
  db:
    image: "postgres:14.4"
    restart: always
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "itsallgood"
      POSTGRES_DB: "travel"
    ports:
      - "5432:5432"
    volumes:
      - db_data_production:/var/lib/postgresql/data
  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - "NODE_ENV=development"
    depends_on:
      - db
    ports:
      - "${HOST_PORT:-8088}:3000"

volumes:
  db_data_production:
