services:
  app:
    # replace `build` line with `image` line, if you want to pull a build generated via github workflow
    # Note you must use the appropriate build tag
    # image: ghcr.io/icefoganalytics/travel-authorization:v2023.11.1.3
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - "${HOST_PORT:-3000}:3000"
    volumes:
      - ./.env:/home/node/app/.env.production
    depends_on:
      - db
  db:
    image: "postgres:14.4"
    restart: always
    env_file:
      - .env
    environment:
      TZ: "UTC"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
