version: "3"

x-default-environment: &default-environment
  NODE_ENV: development
  AUTH0_DOMAIN: "https://dev-0tc6bn14.eu.auth0.com"
  AUTH0_AUDIENCE: testing
  DB_HOST: db
  DB_NAME: &default-db-name travel_development
  DB_PASS: &default-db-password itsallgood
  DB_USER: &default-db-user app
  DB_PORT: 5432

services:
  api:
    build:
      context: ./api
      dockerfile: development.Dockerfile
    env_file:
      - ./api/.env.development
    environment:
      <<: *default-environment
    tty: true # allows attaching debugger, equivalent of docker exec -t
    # stdin_open: true # equivalent of docker exec -i
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/api
    depends_on:
      - db

  db:
    image: "postgres:14.4"
    environment:
      <<: *default-environment
      POSTGRES_USER: *default-db-user
      POSTGRES_PASSWORD: *default-db-password
      POSTGRES_DB: *default-db-name
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
